
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCEndpoint
{
	using global::AbstractEndpoint;
	using global::NuPattern.Runtime;
	using global::System;
	using global::System.Collections.Generic;
	using global::System.ComponentModel;
	using global::System.ComponentModel.Composition;
	using global::System.ComponentModel.Design;
	using global::System.Drawing.Design;
	using Runtime = global::NuPattern.Runtime;

	///	<summary>
	///	Description for AbstractEndpoint.DefaultView.Components.ComponentLink
	///	</summary>
	[Description("Description for AbstractEndpoint.DefaultView.Components.ComponentLink")]
	[ToolkitInterfaceProxy(ExtensionId ="e91869eb-ba2e-4420-baad-df72525d4fe5", DefinitionId = "ab45fb7d-330a-473a-9130-337438f76537", ProxyType = typeof(ComponentLink))]
	[System.CodeDom.Compiler.GeneratedCode("Pattern Toolkit Automation Library", "1.2.19.0")]
	[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal partial class ComponentLink : IComponentLink
	{
		private Runtime.IAbstractElement target;
		private Runtime.IAbstractElementProxy<IComponentLink> proxy;

		/// <summary>
		/// For MEF.
		/// </summary>
		[ImportingConstructor]
		private ComponentLink() { }

		/// <summary>
		/// Initializes a new instance of the <see cref="ComponentLink"/> class.
		/// </summary>
		public ComponentLink(Runtime.IAbstractElement target)
		{
			this.target = target;
			this.proxy = target.ProxyFor<IComponentLink>();
			OnCreated();
		}	

		partial void OnCreated();

		/// <summary>
		/// Gets the parent element.
		/// </summary>
		public virtual IEndpointComponents Parent
		{ 
			get { return this.target.Parent.As<IEndpointComponents>(); }
		}

		/// <summary>
		/// Gets the generic <see cref="Runtime.IElement"/> underlying element.
		/// </summary>
		public virtual Runtime.IElement AsElement()
		{
			return this.As<Runtime.IElement>();
		}

		/// <summary>
		/// Gets the generic underlying element as the given type if possible.
		/// </summary>
		public virtual TRuntimeInterface As<TRuntimeInterface>()
			where TRuntimeInterface : class
		{
			return this.target as TRuntimeInterface;
		}

		///	<summary>
		///	Description for AbstractEndpoint.DefaultView.Components.ComponentLink.ComponentId
		///	</summary>
		[Description("Description for AbstractEndpoint.DefaultView.Components.ComponentLink.ComponentId")]
		[DisplayName("Component Id")]
		[Category("General")]
		public virtual String ComponentId 
		{
			get { return this.proxy.GetValue(() => this.ComponentId); }
			set { this.proxy.SetValue(() => this.ComponentId, value); }
		}

		///	<summary>
		///	Description for AbstractEndpoint.DefaultView.Components.ComponentLink.ComponentName
		///	</summary>
		[Description("Description for AbstractEndpoint.DefaultView.Components.ComponentLink.ComponentName")]
		[DisplayName("Component Name")]
		[Category("General")]
		[TypeConverter(typeof(ComponentReferenceConverter))]
		[Editor(typeof(ComponentReferenceEditor), typeof(UITypeEditor))]
		public virtual String ComponentName 
		{
			get { return this.proxy.GetValue(() => this.ComponentName); }
			set { this.proxy.SetValue(() => this.ComponentName, value); }
		}

		///	<summary>
		///	Description for AbstractEndpoint.DefaultView.Components.ComponentLink.Order
		///	</summary>
		[Description("Description for AbstractEndpoint.DefaultView.Components.ComponentLink.Order")]
		[DisplayName("Order")]
		[Category("General")]
		public virtual Int64 Order 
		{
			get { return this.proxy.GetValue(() => this.Order); }
			set { this.proxy.SetValue(() => this.Order, value); }
		}
		
		///	<summary>
		///	Notes for this element.
		///	</summary>
		[Description("Notes for this element.")]
		[Editor(typeof(MultilineStringEditor), typeof(UITypeEditor))]
		public virtual String Notes 
		{ 
			get { return this.proxy.GetValue(() => this.Notes); }
			set { this.proxy.SetValue(() => this.Notes, value); }
		}
		
		///	<summary>
		///	The InTransaction.
		///	</summary>
		public virtual Boolean InTransaction 
		{ 
			get { return this.proxy.GetValue(() => this.InTransaction); }
		}
		
		///	<summary>
		///	The IsSerializing.
		///	</summary>
		public virtual Boolean IsSerializing 
		{ 
			get { return this.proxy.GetValue(() => this.IsSerializing); }
		}
		
		///	<summary>
		///	The name of this element instance.
		///	</summary>
		[ParenthesizePropertyName(true)]
		[Description("The name of this element instance.")]
		public virtual String InstanceName 
		{ 
			get { return this.proxy.GetValue(() => this.InstanceName); }
			set { this.proxy.SetValue(() => this.InstanceName, value); }
		}
		
		///	<summary>
		///	The order of this element relative to its siblings.
		///	</summary>
		[ReadOnly(true)]
		[Description("The order of this element relative to its siblings.")]
		public virtual Double InstanceOrder 
		{ 
			get { return this.proxy.GetValue(() => this.InstanceOrder); }
			set { this.proxy.SetValue(() => this.InstanceOrder, value); }
		}
		
		///	<summary>
		///	The references of this element.
		///	</summary>
		[Description("The references of this element.")]
		public virtual IEnumerable<IReference> References 
		{ 
			get { return this.proxy.GetValue(() => this.References); }
		}

		/// <summary>
		/// Deletes this instance.
		/// </summary>
		public virtual void Delete()
		{
			this.target.Delete();
		}
	}
}

