
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCEndpoint
{
	using global::NuPattern.Runtime;
	using global::System;
	using global::System.Collections.Generic;
	using global::System.ComponentModel;
	using global::System.ComponentModel.Design;
	using global::System.Drawing.Design;
	using Runtime = global::NuPattern.Runtime;

	///	<summary>
	///	Description for AbstractEndpoint.DefaultView
	///	</summary>
	[Description("Description for AbstractEndpoint.DefaultView")]
	[ToolkitInterface(ExtensionId ="e91869eb-ba2e-4420-baad-df72525d4fe5", DefinitionId = "00aeed68-3b28-4e59-8b91-cefb9ad308a7", ProxyType = typeof(DefaultView))]
	[System.CodeDom.Compiler.GeneratedCode("Pattern Toolkit Automation Library", "1.2.19.0")]
	public partial interface IDefaultView : IToolkitInterface
	{ 
		/// <summary>
		/// Gets the parent element.
		/// </summary>
		IAbstractEndpoint Parent { get; }
		
		/// <summary>
		/// Gets the <see cref="IEndpointComponents"/> contained in this element.
		/// </summary>
		IEndpointComponents EndpointComponents { get; }
		
		/// <summary>
		///	Creates a new <see cref="IEndpointComponents"/>  
		/// executing the optional <paramref name="initializer"/> if not <see langword="null"/>.
		///	</summary>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed")]
		IEndpointComponents CreateEndpointComponents(string name, Action<IEndpointComponents> initializer = null, bool raiseInstantiateEvents = true);
		
		///	<summary>
		///	Deletes this element from the store.
		///	</summary>
		void Delete();

		/// <summary>
		/// Gets the generic <see cref="Runtime.IView"/> underlying element.
		/// </summary>
		Runtime.IView AsView();
	}
}

