//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NServiceBus.Modeling.EndpointDesign
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "endpoints";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"NServiceBus.Modeling.EndpointDesign";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"NServiceBus";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID EndpointDesignDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EndpointDesignCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID EndpointDesignExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EndpointDesignCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewEndpointDesignExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EndpointDesignCommandSetId), 0x0001);
	
		// Package identifier
		public const string EndpointDesignPackageId = "be731d99-2fd0-4514-9d8d-8d803fe6dc4a";
		
		// Editor factory identifier
		public const string EndpointDesignEditorFactoryId = "40762e29-3159-47d9-8766-9501177c7142";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string EndpointDesignModelExplorerToolWindowId = "90bc3db7-ebd2-48b6-b29c-3de758c8c06a";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace NServiceBus.Modeling.EndpointDesign
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string EndpointDesignCommandSetId = "6442ff18-eee6-4680-ab83-4f4059bd5a2e";
	}
}