//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;

namespace OnlineSales.eCommerce.Controllers
{
    // This code is generated by ServiceMatrix
    public class GeneratedWebInitialization : INeedInitialization
    {
        public void Init()
        {
        }
    }
}
