//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace NServiceBus.Modeling.EndpointDesign
{
	/// <summary>
	/// DomainModel EndpointDesignDomainModel
	/// Description for NServiceBus.Modeling.EndpointDesign.EndpointDesign
	/// </summary>
	[DslDesign::DisplayNameResource("NServiceBus.Modeling.EndpointDesign.EndpointDesignDomainModel.DisplayName", typeof(global::NServiceBus.Modeling.EndpointDesign.EndpointDesignDomainModel), "NServiceBus.Modeling.EndpointDesign.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("NServiceBus.Modeling.EndpointDesign.EndpointDesignDomainModel.Description", typeof(global::NServiceBus.Modeling.EndpointDesign.EndpointDesignDomainModel), "NServiceBus.Modeling.EndpointDesign.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("60279b02-26cf-4430-b71e-b1191cba65f9")]
	public partial class EndpointDesignDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// EndpointDesignDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x60279b02, 0x26cf, 0x4430, 0xb7, 0x1e, 0xb1, 0x19, 0x1c, 0xba, 0x65, 0xf9);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public EndpointDesignDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(EndpointModel),
				typeof(SendEndpoint),
				typeof(NamedElement),
				typeof(SendReceiveEndpoint),
				typeof(Event),
				typeof(Command),
				typeof(Endpoint),
				typeof(EndpointModelHasEvents),
				typeof(EndpointModelHasEndpoints),
				typeof(EndpointModelHasCommands),
				typeof(CommandIsProcessedBySendReceiveEndpoint),
				typeof(EventsAreProcessedBySendReceiveEndpoints),
				typeof(SendEndpointEmitsCommands),
				typeof(SendReceiveEndpointEmitsEvents),
				typeof(SendReceiveEndpointEmitCommands),
				typeof(EndpointDesignDiagram),
				typeof(EmitConnector),
				typeof(ProcessConnector),
				typeof(CommandShape),
				typeof(EventShape),
				typeof(SendReceiveEndpointShape),
				typeof(SendEndpointShape),
				typeof(global::NServiceBus.Modeling.EndpointDesign.FixUpDiagram),
				typeof(global::NServiceBus.Modeling.EndpointDesign.DecoratorPropertyChanged),
				typeof(global::NServiceBus.Modeling.EndpointDesign.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(NamedElement), "Name", NamedElement.NameDomainPropertyId, typeof(NamedElement.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Endpoint), "Type", Endpoint.TypeDomainPropertyId, typeof(Endpoint.TypePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(EndpointModelHasEvents), "EndpointModel", EndpointModelHasEvents.EndpointModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EndpointModelHasEvents), "Event", EndpointModelHasEvents.EventDomainRoleId),
				new DomainRolePlayerInfo(typeof(EndpointModelHasEndpoints), "EndpointModel", EndpointModelHasEndpoints.EndpointModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EndpointModelHasEndpoints), "Endpoint", EndpointModelHasEndpoints.EndpointDomainRoleId),
				new DomainRolePlayerInfo(typeof(EndpointModelHasCommands), "EndpointModel", EndpointModelHasCommands.EndpointModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EndpointModelHasCommands), "Command", EndpointModelHasCommands.CommandDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommandIsProcessedBySendReceiveEndpoint), "Command", CommandIsProcessedBySendReceiveEndpoint.CommandDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommandIsProcessedBySendReceiveEndpoint), "SendReceiveEndpoint", CommandIsProcessedBySendReceiveEndpoint.SendReceiveEndpointDomainRoleId),
				new DomainRolePlayerInfo(typeof(EventsAreProcessedBySendReceiveEndpoints), "Event", EventsAreProcessedBySendReceiveEndpoints.EventDomainRoleId),
				new DomainRolePlayerInfo(typeof(EventsAreProcessedBySendReceiveEndpoints), "SendReceiveEndpoint", EventsAreProcessedBySendReceiveEndpoints.SendReceiveEndpointDomainRoleId),
				new DomainRolePlayerInfo(typeof(SendEndpointEmitsCommands), "SendEndpoint", SendEndpointEmitsCommands.SendEndpointDomainRoleId),
				new DomainRolePlayerInfo(typeof(SendEndpointEmitsCommands), "Command", SendEndpointEmitsCommands.CommandDomainRoleId),
				new DomainRolePlayerInfo(typeof(SendReceiveEndpointEmitsEvents), "SendReceiveEndpoint", SendReceiveEndpointEmitsEvents.SendReceiveEndpointDomainRoleId),
				new DomainRolePlayerInfo(typeof(SendReceiveEndpointEmitsEvents), "Event", SendReceiveEndpointEmitsEvents.EventDomainRoleId),
				new DomainRolePlayerInfo(typeof(SendReceiveEndpointEmitCommands), "SendReceiveEndpoint", SendReceiveEndpointEmitCommands.SendReceiveEndpointDomainRoleId),
				new DomainRolePlayerInfo(typeof(SendReceiveEndpointEmitCommands), "Command", SendReceiveEndpointEmitCommands.CommandDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(14);
				createElementMap.Add(typeof(EndpointModel), 0);
				createElementMap.Add(typeof(SendEndpoint), 1);
				createElementMap.Add(typeof(SendReceiveEndpoint), 2);
				createElementMap.Add(typeof(Event), 3);
				createElementMap.Add(typeof(Command), 4);
				createElementMap.Add(typeof(EndpointDesignDiagram), 5);
				createElementMap.Add(typeof(EmitConnector), 6);
				createElementMap.Add(typeof(ProcessConnector), 7);
				createElementMap.Add(typeof(CommandShape), 8);
				createElementMap.Add(typeof(EventShape), 9);
				createElementMap.Add(typeof(SendReceiveEndpointShape), 10);
				createElementMap.Add(typeof(SendEndpointShape), 11);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::NServiceBus.Modeling.EndpointDesign.EndpointDesignDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new EndpointModel(partition, propertyAssignments);
				case 1: return new SendEndpoint(partition, propertyAssignments);
				case 2: return new SendReceiveEndpoint(partition, propertyAssignments);
				case 3: return new Event(partition, propertyAssignments);
				case 4: return new Command(partition, propertyAssignments);
				case 5: return new EndpointDesignDiagram(partition, propertyAssignments);
				case 6: return new EmitConnector(partition, propertyAssignments);
				case 7: return new ProcessConnector(partition, propertyAssignments);
				case 8: return new CommandShape(partition, propertyAssignments);
				case 9: return new EventShape(partition, propertyAssignments);
				case 10: return new SendReceiveEndpointShape(partition, propertyAssignments);
				case 11: return new SendEndpointShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8);
				createElementLinkMap.Add(typeof(EndpointModelHasEvents), 0);
				createElementLinkMap.Add(typeof(EndpointModelHasEndpoints), 1);
				createElementLinkMap.Add(typeof(EndpointModelHasCommands), 2);
				createElementLinkMap.Add(typeof(CommandIsProcessedBySendReceiveEndpoint), 3);
				createElementLinkMap.Add(typeof(EventsAreProcessedBySendReceiveEndpoints), 4);
				createElementLinkMap.Add(typeof(SendEndpointEmitsCommands), 5);
				createElementLinkMap.Add(typeof(SendReceiveEndpointEmitsEvents), 6);
				createElementLinkMap.Add(typeof(SendReceiveEndpointEmitCommands), 7);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::NServiceBus.Modeling.EndpointDesign.EndpointDesignDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new EndpointModelHasEvents(partition, roleAssignments, propertyAssignments);
				case 1: return new EndpointModelHasEndpoints(partition, roleAssignments, propertyAssignments);
				case 2: return new EndpointModelHasCommands(partition, roleAssignments, propertyAssignments);
				case 3: return new CommandIsProcessedBySendReceiveEndpoint(partition, roleAssignments, propertyAssignments);
				case 4: return new EventsAreProcessedBySendReceiveEndpoints(partition, roleAssignments, propertyAssignments);
				case 5: return new SendEndpointEmitsCommands(partition, roleAssignments, propertyAssignments);
				case 6: return new SendReceiveEndpointEmitsEvents(partition, roleAssignments, propertyAssignments);
				case 7: return new SendReceiveEndpointEmitCommands(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "NServiceBus.Modeling.EndpointDesign.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return EndpointDesignDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (EndpointDesignDomainModel.resourceManager == null)
				{
					EndpointDesignDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(EndpointDesignDomainModel).Assembly);
				}
				return EndpointDesignDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return EndpointDesignDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return EndpointDesignDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (EndpointDesignDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new EndpointDesignCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					EndpointDesignDomainModel.copyClosure = copyFilter;
				}
				return EndpointDesignDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (EndpointDesignDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new EndpointDesignDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					EndpointDesignDomainModel.removeClosure = removeFilter;
				}
				return EndpointDesignDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::NServiceBus.Modeling.EndpointDesign.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::NServiceBus.Modeling.EndpointDesign.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::NServiceBus.Modeling.EndpointDesign.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::NServiceBus.Modeling.EndpointDesign.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::NServiceBus.Modeling.EndpointDesign.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::NServiceBus.Modeling.EndpointDesign.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class EndpointDesignDeleteClosure : EndpointDesignDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public EndpointDesignDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class EndpointDesignDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public EndpointDesignDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::NServiceBus.Modeling.EndpointDesign.EndpointModelHasEvents.EventDomainRoleId, true);
			DomainRoles.Add(global::NServiceBus.Modeling.EndpointDesign.EndpointModelHasEndpoints.EndpointDomainRoleId, true);
			DomainRoles.Add(global::NServiceBus.Modeling.EndpointDesign.EndpointModelHasCommands.CommandDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class EndpointDesignCopyClosure : EndpointDesignCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public EndpointDesignCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class EndpointDesignCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public EndpointDesignCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

