//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.TeamArchitect.PowerTools.Features;

namespace NServiceBusStudio.Guidance
{
	/// <summary>
	/// Defines a base class for the guidance workflow for this feature.
	/// </summary>
	[CLSCompliant(false)]
	[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	[System.CodeDom.Compiler.GeneratedCode("NuPattern Toolkit Builder VS2012", "1.3.20.0")]
	public partial class ProcessWorkflow : GuidanceWorkflow
	{
		/// <summary>
		/// Gets the feature composition service.
		/// </summary>
		[Import]
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		private IFeatureCompositionService FeatureComposition
		{
			get;
			set;
		}

		/// <summary>
		/// Gets whether to ignore all post conditions and enable all actions.
		/// </summary>
		public override bool IgnorePostConditions
		{
			get
			{
				return true;
			}
		}

		/// <summary>
		/// Initializes the workflow.
		/// </summary>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals")]
		protected override void OnInitialize()
		{
			base.OnInitialize();
			this.Name = "GuidanceWorkflow";
			var initial1 = new Initial
			{
				Name = "NServiceBus Studio Guidance",
			};
			this.ConnectTo(initial1);
			var fork2 = new Fork
			{
				Name = "Getting Started",
			};
			initial1.ConnectTo(fork2);
			var guidanceaction3 = new GuidanceAction
			{
				Name = "Creating A New Project",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/CreatingANewProject.mht",
			};
			fork2.ConnectTo(guidanceaction3);
			var guidanceaction4 = new GuidanceAction
			{
				Name = "Fault Tolerance",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/FaultTolerance.mht",
			};
			guidanceaction3.ConnectTo(guidanceaction4);
			var guidanceaction5 = new GuidanceAction
			{
				Name = "Publish / Subscribe Communication",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/PublishSubscribeCommunication.mht",
			};
			guidanceaction4.ConnectTo(guidanceaction5);
			var guidanceaction6 = new GuidanceAction
			{
				Name = "NServiceBus Videos",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NServiceBusVideos.mht",
			};
			guidanceaction5.ConnectTo(guidanceaction6);
			var guidanceaction7 = new GuidanceAction
			{
				Name = "Overview",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/Overview.mht",
			};
			guidanceaction6.ConnectTo(guidanceaction7);
			var guidanceaction8 = new GuidanceAction
			{
				Name = "Architectural Principles",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/ArchitecturalPrinciples.mht",
			};
			guidanceaction7.ConnectTo(guidanceaction8);
			var guidanceaction9 = new GuidanceAction
			{
				Name = "Transactions & Message Processing",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/TransactionsMessageProcessing.mht",
			};
			guidanceaction8.ConnectTo(guidanceaction9);
			var guidanceaction10 = new GuidanceAction
			{
				Name = "Building NServiceBus From Source Files",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/BuildingNServiceBusFromSourceFiles.mht",
			};
			guidanceaction9.ConnectTo(guidanceaction10);
			var guidanceaction11 = new GuidanceAction
			{
				Name = "NServiceBus And WCF",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NServiceBusAndWCF.mht",
			};
			guidanceaction10.ConnectTo(guidanceaction11);
			var guidanceaction12 = new GuidanceAction
			{
				Name = "NServiceBus And WebSphere/Sonic",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NServiceBusAndWebSphereSonic.mht",
			};
			guidanceaction11.ConnectTo(guidanceaction12);
			var guidanceaction13 = new GuidanceAction
			{
				Name = "Containers",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/Containers.mht",
			};
			guidanceaction12.ConnectTo(guidanceaction13);
			var guidanceaction14 = new GuidanceAction
			{
				Name = "NServiceBus Support For Child Containers",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NServiceBusSupportForChildContainers.mht",
			};
			guidanceaction13.ConnectTo(guidanceaction14);
			var guidanceaction15 = new GuidanceAction
			{
				Name = "Logging In NServiceBus v.3",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/LoggingInNServiceBusv3.mht",
			};
			guidanceaction14.ConnectTo(guidanceaction15);
			var guidanceaction16 = new GuidanceAction
			{
				Name = "Messages As Intefaces",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/MessagesAsIntefaces.mht",
			};
			guidanceaction15.ConnectTo(guidanceaction16);
			var guidanceaction17 = new GuidanceAction
			{
				Name = "Introducing IEvent And ICommand",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/IntroducingIEventAndICommand.mht",
			};
			guidanceaction16.ConnectTo(guidanceaction17);
			var guidanceaction18 = new GuidanceAction
			{
				Name = "Staying Updated With NuGet",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/StayingUpdatedWithNuGet.mht",
			};
			guidanceaction17.ConnectTo(guidanceaction18);
			var guidanceaction19 = new GuidanceAction
			{
				Name = "Unobtrusive Mode Messages",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UnobtrusiveModeMessages.mht",
			};
			guidanceaction18.ConnectTo(guidanceaction19);
			var guidanceaction20 = new GuidanceAction
			{
				Name = "Unit Testing",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UnitTesting.mht",
			};
			guidanceaction19.ConnectTo(guidanceaction20);
			var guidanceaction21 = new GuidanceAction
			{
				Name = "One Way/Send Only Endpoints",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/OneWaySendOnlyEndpoints.mht",
			};
			guidanceaction20.ConnectTo(guidanceaction21);
			var guidanceaction22 = new GuidanceAction
			{
				Name = "Scheduling With NServiceBus",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/SchedulingWithNServiceBus.mht",
			};
			guidanceaction21.ConnectTo(guidanceaction22);
			var join23 = new Join
			{
				Name = "Join1",
			};
			guidanceaction22.ConnectTo(join23);
			var fork24 = new Fork
			{
				Name = "Hosting",
			};
			join23.ConnectTo(fork24);
			var guidanceaction25 = new GuidanceAction
			{
				Name = "The NServiceBus Host",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/TheNServiceBusHost.mht",
			};
			fork24.ConnectTo(guidanceaction25);
			var guidanceaction26 = new GuidanceAction
			{
				Name = "Hosting NServiceBus In Your Own Process",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HostingNServiceBusInYourOwnProcess.mht",
			};
			guidanceaction25.ConnectTo(guidanceaction26);
			var guidanceaction27 = new GuidanceAction
			{
				Name = "Profiles For NServiceBus Host",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/ProfilesForNServiceBusHost.mht",
			};
			guidanceaction26.ConnectTo(guidanceaction27);
			var guidanceaction28 = new GuidanceAction
			{
				Name = "More On Profiles",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/MoreOnProfiles.mht",
			};
			guidanceaction27.ConnectTo(guidanceaction28);
			var guidanceaction29 = new GuidanceAction
			{
				Name = "NServiceBus 32-bit (x86) Host Process",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NServiceBus32bitx86HostProcess.mht",
			};
			guidanceaction28.ConnectTo(guidanceaction29);
			var join30 = new Join
			{
				Name = "Join2",
			};
			guidanceaction29.ConnectTo(join30);
			var fork31 = new Fork
			{
				Name = "Persistence",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/Persistence.mht",
			};
			join30.ConnectTo(fork31);
			var guidanceaction32 = new GuidanceAction
			{
				Name = "Persistence In NServiceBus ",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/PersistenceInNServiceBus.mht",
			};
			fork31.ConnectTo(guidanceaction32);
			var guidanceaction33 = new GuidanceAction
			{
				Name = "Using RavenDB In NServiceBus – Installing",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UsingRavenDBInNServiceBusInstalling.mht",
			};
			guidanceaction32.ConnectTo(guidanceaction33);
			var guidanceaction34 = new GuidanceAction
			{
				Name = "Using RavenDB In NServiceBus – Connecting",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UsingRavenDBInNServiceBusConnecting.mht",
			};
			guidanceaction33.ConnectTo(guidanceaction34);
			var guidanceaction35 = new GuidanceAction
			{
				Name = "Relational Persistence Using NHibernate",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/RelationalPersistenceUsingNHibernate.mht",
			};
			guidanceaction34.ConnectTo(guidanceaction35);
			var join36 = new Join
			{
				Name = "Join3",
			};
			guidanceaction35.ConnectTo(join36);
			var fork37 = new Fork
			{
				Name = "Scaling Out",
			};
			join36.ConnectTo(fork37);
			var guidanceaction38 = new GuidanceAction
			{
				Name = "Performance",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/Performance.mht",
			};
			fork37.ConnectTo(guidanceaction38);
			var guidanceaction39 = new GuidanceAction
			{
				Name = "The Gateway And Multi-Site Distribution",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/TheGatewayAndMultiSiteDistribution.mht",
			};
			guidanceaction38.ConnectTo(guidanceaction39);
			var guidanceaction40 = new GuidanceAction
			{
				Name = "Load Balancing With The Distributor",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/LoadBalancingWithTheDistributor.mht",
			};
			guidanceaction39.ConnectTo(guidanceaction40);
			var guidanceaction41 = new GuidanceAction
			{
				Name = "Unit Of Work In NServiceBus",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UnitOfWorkInNServiceBus.mht",
			};
			guidanceaction40.ConnectTo(guidanceaction41);
			var guidanceaction42 = new GuidanceAction
			{
				Name = "Unit Of Work Implementation For RavenDB",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UnitOfWorkImplementationForRavenDB.mht",
			};
			guidanceaction41.ConnectTo(guidanceaction42);
			var guidanceaction43 = new GuidanceAction
			{
				Name = "Introduction To The Gateway",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/IntroductionToTheGateway.mht",
			};
			guidanceaction42.ConnectTo(guidanceaction43);
			var guidanceaction44 = new GuidanceAction
			{
				Name = "Deploying NServiceBus In A Windows Failover Cluster",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/DeployingNServiceBusInAWindowsFailoverCluster.mht",
			};
			guidanceaction43.ConnectTo(guidanceaction44);
			var join45 = new Join
			{
				Name = "Join4",
			};
			guidanceaction44.ConnectTo(join45);
			var fork46 = new Fork
			{
				Name = "Long-Running Processes",
			};
			join45.ConnectTo(fork46);
			var guidanceaction47 = new GuidanceAction
			{
				Name = "Sagas In NServiceBus",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/SagasInNServiceBus.mht",
			};
			fork46.ConnectTo(guidanceaction47);
			var guidanceaction48 = new GuidanceAction
			{
				Name = "NServiceBus Sagas And Concurrency",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NServiceBusSagasAndConcurrency.mht",
			};
			guidanceaction47.ConnectTo(guidanceaction48);
			var join49 = new Join
			{
				Name = "Join5",
			};
			guidanceaction48.ConnectTo(join49);
			var fork50 = new Fork
			{
				Name = "Publish-Subscribe",
			};
			join49.ConnectTo(fork50);
			var guidanceaction51 = new GuidanceAction
			{
				Name = "How Pub/Sub Works",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowPubSubWorks.mht",
			};
			fork50.ConnectTo(guidanceaction51);
			var guidanceaction52 = new GuidanceAction
			{
				Name = "Publish/Subscribe Configuration",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/PublishSubscribeConfiguration.mht",
			};
			guidanceaction51.ConnectTo(guidanceaction52);
			var join53 = new Join
			{
				Name = "Join6",
			};
			guidanceaction52.ConnectTo(join53);
			var fork54 = new Fork
			{
				Name = "Customization",
			};
			join53.ConnectTo(fork54);
			var guidanceaction55 = new GuidanceAction
			{
				Name = "Customizing NServiceBus Configuration",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/CustomizingNServiceBusConfiguration.mht",
			};
			fork54.ConnectTo(guidanceaction55);
			var guidanceaction56 = new GuidanceAction
			{
				Name = "Pipeline Management Using Message Mutators",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/PipelineManagementUsingMessageMutators.mht",
			};
			guidanceaction55.ConnectTo(guidanceaction56);
			var join57 = new Join
			{
				Name = "Join7",
			};
			guidanceaction56.ConnectTo(join57);
			var fork58 = new Fork
			{
				Name = "Versioning",
			};
			join57.ConnectTo(fork58);
			var guidanceaction59 = new GuidanceAction
			{
				Name = "Migrating To NServiceBus 3.0 – Timeouts",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/MigratingToNServiceBus30Timeouts.mht",
			};
			fork58.ConnectTo(guidanceaction59);
			var guidanceaction60 = new GuidanceAction
			{
				Name = "Potential Issues Updating NSB Studio On Visual Studio 11 Beta",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/PotentialIssuesUpdatingNSBStudioOnVisualStudio11Beta.mht",
			};
			guidanceaction59.ConnectTo(guidanceaction60);
			var guidanceaction61 = new GuidanceAction
			{
				Name = "Management And Monitoring",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/ManagementAndMonitoring.mht",
			};
			guidanceaction60.ConnectTo(guidanceaction61);
			var guidanceaction62 = new GuidanceAction
			{
				Name = "Auditing With NServiceBus",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/AuditingWithNServiceBus.mht",
			};
			guidanceaction61.ConnectTo(guidanceaction62);
			var guidanceaction63 = new GuidanceAction
			{
				Name = "Monitoring NServiceBus Endpoints",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/MonitoringNServiceBusEndpoints.mht",
			};
			guidanceaction62.ConnectTo(guidanceaction63);
			var guidanceaction64 = new GuidanceAction
			{
				Name = "MSMQ Information",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/MSMQInformation.mht",
			};
			guidanceaction63.ConnectTo(guidanceaction64);
			var join65 = new Join
			{
				Name = "Join8",
			};
			guidanceaction64.ConnectTo(join65);
			var fork66 = new Fork
			{
				Name = "FAQ",
			};
			join65.ConnectTo(fork66);
			var guidanceaction67 = new GuidanceAction
			{
				Name = "How Do I Define A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIDefineAMessage.mht",
			};
			fork66.ConnectTo(guidanceaction67);
			var guidanceaction68 = new GuidanceAction
			{
				Name = "How Do I Specify Store & Forward For A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoISpecifyStoreForwardForAMessage.mht",
			};
			guidanceaction67.ConnectTo(guidanceaction68);
			var guidanceaction69 = new GuidanceAction
			{
				Name = "How Do I Discard Old Messages?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIDiscardOldMessages.mht",
			};
			guidanceaction68.ConnectTo(guidanceaction69);
			var guidanceaction70 = new GuidanceAction
			{
				Name = "How Do I Instantiate A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIInstantiateAMessage.mht",
			};
			guidanceaction69.ConnectTo(guidanceaction70);
			var guidanceaction71 = new GuidanceAction
			{
				Name = "How Do I Send A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoISendAMessage.mht",
			};
			guidanceaction70.ConnectTo(guidanceaction71);
			var guidanceaction72 = new GuidanceAction
			{
				Name = "How Do I Specify To Which Destination A Message Will Be Sent?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoISpecifyToWhichDestinationAMessageWillBeSent.mht",
			};
			guidanceaction71.ConnectTo(guidanceaction72);
			var guidanceaction73 = new GuidanceAction
			{
				Name = "How Can I See The Queues And Messages On A Machine?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowCanISeeTheQueuesAndMessagesOnAMachine.mht",
			};
			guidanceaction72.ConnectTo(guidanceaction73);
			var guidanceaction74 = new GuidanceAction
			{
				Name = "How Do I Handle A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIHandleAMessage.mht",
			};
			guidanceaction73.ConnectTo(guidanceaction74);
			var guidanceaction75 = new GuidanceAction
			{
				Name = "How Do I Specify The Order In Which Handlers Are Invoked?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoISpecifyTheOrderInWhichHandlersAreInvoked.mht",
			};
			guidanceaction74.ConnectTo(guidanceaction75);
			var guidanceaction76 = new GuidanceAction
			{
				Name = "How Do I Get A Reference To IBus In My Message Handler?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIGetAReferenceToIBusInMyMessageHandler.mht",
			};
			guidanceaction75.ConnectTo(guidanceaction76);
			var guidanceaction77 = new GuidanceAction
			{
				Name = "How Do I Get Technical Information About A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIGetTechnicalInformationAboutAMessage.mht",
			};
			guidanceaction76.ConnectTo(guidanceaction77);
			var guidanceaction78 = new GuidanceAction
			{
				Name = "How Do I Reply To A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIReplyToAMessage.mht",
			};
			guidanceaction77.ConnectTo(guidanceaction78);
			var guidanceaction79 = new GuidanceAction
			{
				Name = "How Do I Handle Responses At Client-side?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIHandleResponsesAtClientside.mht",
			};
			guidanceaction78.ConnectTo(guidanceaction79);
			var guidanceaction80 = new GuidanceAction
			{
				Name = "How Do I Publish A Message?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIPublishAMessage.mht",
			};
			guidanceaction79.ConnectTo(guidanceaction80);
			var guidanceaction81 = new GuidanceAction
			{
				Name = "How Do I Handle Exceptions?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIHandleExceptions.mht",
			};
			guidanceaction80.ConnectTo(guidanceaction81);
			var guidanceaction82 = new GuidanceAction
			{
				Name = "How Do I Expose An NServiceBus Endpoint As A Web/Wcf Service?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoIExposeAnNServiceBusEndpointAsAWebWcfService.mht",
			};
			guidanceaction81.ConnectTo(guidanceaction82);
			var guidanceaction83 = new GuidanceAction
			{
				Name = "Type Was Not Registered In The Serializer",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/TypeWasNotRegisteredInTheSerializer.mht",
			};
			guidanceaction82.ConnectTo(guidanceaction83);
			var guidanceaction84 = new GuidanceAction
			{
				Name = "MessageQueueException: Insufficient resources to perform operation",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/MessageQueueExceptionInsufficientresourcestoperformoperation.mht",
			};
			guidanceaction83.ConnectTo(guidanceaction84);
			var guidanceaction85 = new GuidanceAction
			{
				Name = "How To Specify Your Input Queue Name?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowToSpecifyYourInputQueueName.mht",
			};
			guidanceaction84.ConnectTo(guidanceaction85);
			var guidanceaction86 = new GuidanceAction
			{
				Name = "In A Distributor Scenario, What Happens To The Message If A Worker Goe...",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/InADistributorScenarioWhatHappensToTheMessageIfAWorkerGoe.mht",
			};
			guidanceaction85.ConnectTo(guidanceaction86);
			var guidanceaction87 = new GuidanceAction
			{
				Name = "RunMeFirst.bat Throws An Exception",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/RunMeFirstbatThrowsAnException.mht",
			};
			guidanceaction86.ConnectTo(guidanceaction87);
			var guidanceaction88 = new GuidanceAction
			{
				Name = "No endpoint Configuration Found In Scanned Assemblies Exception",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NoendpointConfigurationFoundInScannedAssembliesException.mht",
			};
			guidanceaction87.ConnectTo(guidanceaction88);
			var guidanceaction89 = new GuidanceAction
			{
				Name = "DTCPIng WARNING: the CID values for both test machines are the same",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/DTCPIngWARNINGtheCIDvaluesforbothtestmachinesarethesame.mht",
			};
			guidanceaction88.ConnectTo(guidanceaction89);
			var guidanceaction90 = new GuidanceAction
			{
				Name = "Why You Can't Use NLB With MSMQ",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/WhyYouCantUseNLBWithMSMQ.mht",
			};
			guidanceaction89.ConnectTo(guidanceaction90);
			var guidanceaction91 = new GuidanceAction
			{
				Name = "Configuring AWS For NServiceBus",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/ConfiguringAWSForNServiceBus.mht",
			};
			guidanceaction90.ConnectTo(guidanceaction91);
			var guidanceaction92 = new GuidanceAction
			{
				Name = "Licensing And Distribution",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/LicensingAndDistribution.mht",
			};
			guidanceaction91.ConnectTo(guidanceaction92);
			var guidanceaction93 = new GuidanceAction
			{
				Name = "How To Debug RavenDB Through Fiddler Using NServiceBus",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowToDebugRavenDBThroughFiddlerUsingNServiceBus.mht",
			};
			guidanceaction92.ConnectTo(guidanceaction93);
			var guidanceaction94 = new GuidanceAction
			{
				Name = "How Do I Centralize All Unobtrusive Declarations?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HowDoICentralizeAllUnobtrusiveDeclarations.mht",
			};
			guidanceaction93.ConnectTo(guidanceaction94);
			var guidanceaction95 = new GuidanceAction
			{
				Name = "DefiningMessagesAs And Exception When Starting Endpoint",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/DefiningMessagesAsAndExceptionWhenStartingEndpoint.mht",
			};
			guidanceaction94.ConnectTo(guidanceaction95);
			var guidanceaction96 = new GuidanceAction
			{
				Name = "RunMeFirst.bat Hangs",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/RunMeFirstbatHangs.mht",
			};
			guidanceaction95.ConnectTo(guidanceaction96);
			var guidanceaction97 = new GuidanceAction
			{
				Name = "Ho Do I Reduce Throughput Of an Endpoint?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/HoDoIReduceThroughputOfanEndpoint.mht",
			};
			guidanceaction96.ConnectTo(guidanceaction97);
			var guidanceaction98 = new GuidanceAction
			{
				Name = "Does NServiceBus Supports Both Native And Non-Native Connectivity?",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/DoesNServiceBusSupportsBothNativeAndNonNativeConnectivity.mht",
			};
			guidanceaction97.ConnectTo(guidanceaction98);
			var guidanceaction99 = new GuidanceAction
			{
				Name = "InvalidOperationException In Unobtrusive Mode",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/InvalidOperationExceptionInUnobtrusiveMode.mht",
			};
			guidanceaction98.ConnectTo(guidanceaction99);
			var join100 = new Join
			{
				Name = "Join9",
			};
			guidanceaction99.ConnectTo(join100);
			var fork101 = new Fork
			{
				Name = "Samples",
			};
			join100.ConnectTo(fork101);
			var guidanceaction102 = new GuidanceAction
			{
				Name = "Full Duplex Sample v.3",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/FullDuplexSamplev3.mht",
			};
			fork101.ConnectTo(guidanceaction102);
			var guidanceaction103 = new GuidanceAction
			{
				Name = "Publish/Subscribe Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/PublishSubscribeSample.mht",
			};
			guidanceaction102.ConnectTo(guidanceaction103);
			var guidanceaction104 = new GuidanceAction
			{
				Name = "Unobtrusive Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UnobtrusiveSample.mht",
			};
			guidanceaction103.ConnectTo(guidanceaction104);
			var guidanceaction105 = new GuidanceAction
			{
				Name = "Scale Out Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/ScaleOutSample.mht",
			};
			guidanceaction104.ConnectTo(guidanceaction105);
			var guidanceaction106 = new GuidanceAction
			{
				Name = "Using NServiceBus in a ASP.NET Web Application",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UsingNServiceBusinaASPNETWebApplication.mht",
			};
			guidanceaction105.ConnectTo(guidanceaction106);
			var guidanceaction107 = new GuidanceAction
			{
				Name = "Using NServiceBus with ASP.NET MVC",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/UsingNServiceBuswithASPNETMVC.mht",
			};
			guidanceaction106.ConnectTo(guidanceaction107);
			var guidanceaction108 = new GuidanceAction
			{
				Name = "Injecting The Bus Into Asp.Net MVC Controller",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/InjectingTheBusIntoAspNetMVCController.mht",
			};
			guidanceaction107.ConnectTo(guidanceaction108);
			var guidanceaction109 = new GuidanceAction
			{
				Name = "Encryption Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/EncryptionSample.mht",
			};
			guidanceaction108.ConnectTo(guidanceaction109);
			var guidanceaction110 = new GuidanceAction
			{
				Name = "Generic Host Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/GenericHostSample.mht",
			};
			guidanceaction109.ConnectTo(guidanceaction110);
			var guidanceaction111 = new GuidanceAction
			{
				Name = "Versioning Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/VersioningSample.mht",
			};
			guidanceaction110.ConnectTo(guidanceaction111);
			var guidanceaction112 = new GuidanceAction
			{
				Name = "NServiceBus Message Mutators Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/NServiceBusMessageMutatorsSample.mht",
			};
			guidanceaction111.ConnectTo(guidanceaction112);
			var guidanceaction113 = new GuidanceAction
			{
				Name = "Attachments / DataBus Sample",
				Link = "content://a5e9f15b-ad7f-4201-851e-186dd8db3bc9/GeneratedCode/Guidance/Content/AttachmentsDataBusSample.mht",
			};
			guidanceaction112.ConnectTo(guidanceaction113);
			var join114 = new Join
			{
				Name = "Join10",
			};
			guidanceaction113.ConnectTo(join114);
			var final115 = new Final
			{
				Name = "ActivityFinal1",
			};
			join114.ConnectTo(final115);

			this.OnPostInitialize();
		}

		partial void OnPostInitialize();
	}

	/// <summary>
	/// Defines the feature extension containing the guidance workflow.
	/// </summary>
	[Feature("a5e9f15b-ad7f-4201-851e-186dd8db3bc9", DefaultName="Working with NServiceBus Studio")]
	[Export(typeof(IFeatureExtension))]
	[PartCreationPolicy(CreationPolicy.NonShared)]
	[CLSCompliant(false)]
	[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	[System.CodeDom.Compiler.GeneratedCode("NuPattern Toolkit Builder VS2012", "1.3.20.0")]
	public partial class Feature : BlackboardFeatureExtension<ProcessWorkflow>
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="Feature"/> class.
		/// </summary>
		public Feature()
			: base()
		{
		}

		/// <summary>
		/// Gets or sets the ServiceProvider.
		/// </summary>
		[Import]
		public SVsServiceProvider ServiceProvider { get; set; }
	}
}

